### ISSUE TITLE
could not build project after clone shows error

### ISSUE THREAD

**Issue by anantshah93** [layerhq/Atlas-Android-Messenger#15]
![screen shot 2016-03-25 at 18 31 19](https://cloud.githubusercontent.com/assets/13238619/14044536/dd5fc4bc-f2b7-11e5-947a-5a7811a0de20.png)
Error:A problem occurred configuring project ':app'.
> Cannot evaluate module layer-atlas : Configuration with name 'default' not found.

even not showing build varients see screen shot

**Comment by muafakul** [comment]
same as me

**Comment by maju6406** [comment]
You need to run

git submodule update --init

in the project folder. See the Setup section in the README:
https://github.com/layerhq/Atlas-Android-Messenger#setup

**Comment by anantshah93** [comment]
thank you for your support Done!!! thanks
