### ISSUE TITLE
How to set display_name and avatar_url when user register 

### ISSUE THREAD

**Issue by rakshitsoni02** [layerhq/Atlas-Android-Messenger#18]
i am getting null or "" in response from heroku json response as i am setting avatar_url in credentials please help me how to set or update user image and name like whatsapp i need these values while fetching participants.

**Comment by PratapOdedara** [comment]
Don't relay on heroku providers just register users on your own server and get all info from there then it will work fine

**Comment by feifanzhou** [comment]
@rakshitsoni02 not sure what your Heroku app is doing, but make sure your identity token [includes the `avatar_url` field](https://developer.layer.com/docs/ios/guides#step-3-post-the-nonce-and-generate-identity-token) (Link is to the iOS docs, but the identity token is the same for an Android app).
