### ISSUE TITLE
Size issue

### ISSUE THREAD

**Issue by PratapOdedara** [layerhq/Atlas-Android-Messenger#21]
When I send Videos and large images using atlas android messenger application's size increases how to save videos and images in external memory so that size of application won't increase

**Comment by sriamar** [comment]
Hello,

Atlas Android doesn't support video. If you are using large images, we do compress the image and attach a preview. We also hold onto the original image. You can follow 
https://github.com/layerhq/Atlas-Android/tree/master/layer-atlas/src/main/java/com/layer/atlas/messagetypes/threepartimage
and modify it to not store the original image for your case. That would require you to fork Atlas-Android code.

We do use the temporary storage provided by OS, but we don't store in external directory. This needs to be done for SDK. We will consider that, but it won't be happening right away.

Thanks
Amar

**Comment by sriamar** [comment]
Hi @PratapOdedara

It has been a while since this issue is opened. I hope the above reply helps someone looking for an answer. For a faster response, please contact our support from www.layer.com. 

I am closing this particular issue.
