### ISSUE TITLE
Android Studio Gradle Configuration with name 'default' not found

### ISSUE THREAD

**Issue by daniel0x7CC** [layerhq/Atlas-Android-Messenger#26]
Hi, I just cloned this project and I'm getting this issue. What's wrong? ):

**Comment by namsiiii** [comment]
git submodule update --init --recursive

**Comment by krn1** [comment]
can we use this with maven directly without having to do any submodule ?

**Comment by thecombatwombat** [comment]
Thanks @namsiiii for the answer there, and my apologies for the late response to this. 

Yes, you need to update/clone the submodule. We've updated the `README` to reflect this. 
https://github.com/layerhq/Atlas-Android-Messenger/blob/develop/README.md#setup

**Comment by thecombatwombat** [comment]
@krn1 Are you looking to use [Atlas-Android](https://github.com/layerhq/Atlas-Android)? You should be able to pull that in as a dependency via gradle.
