### ISSUE TITLE
Applying Search Filter On Conversation List

### ISSUE THREAD

**Issue by shashank090789** [layerhq/Atlas-Android-Messenger#32]
How to apply search filter on conversation list

**Comment by ajaykk50** [comment]
I am facing the same issue

**Comment by smpete** [comment]
Unfortunately this is not current supported in Atlas. You will need to fork the Atlas repository and add a `setQuery()` method to that class. This should be similar to `AtlasMessagesAdapter.setQuery()`. You can then set a query based on the text in your search field. If you would like to contribute an improvement to the Atlas repository then please open a pull request there.
