### ISSUE TITLE
Default FirebaseApp is not initialized 

### ISSUE THREAD

**Issue by nicholas-jomo** [layerhq/Atlas-Android-Messenger#58]
This crash isn't device related, `FirebaseApp` was not setup properly

Steps:
1. Entered AppID
2. Using providerDemo Flavor
3. Launch App and the follow Crash log will be shown.

Devices:
Samsung Note 2 OS 4.4.2
Samsung Galaxy S5 OS 6.0.1

```
 FATAL EXCEPTION: pool-11-thread-1
 Process: com.layer.messenger.providerdemo, PID: 27653
 java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.layer.messenger.providerdemo. Make sure to call FirebaseApp.initializeApp(Context) first.
     at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
     at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
     at com.layer.sdk.lsdka.lsdkg.a.g(FcmRegistrationManager.java:219)
     at com.layer.sdk.lsdka.lsdkg.a.a(FcmRegistrationManager.java:68)
     at com.layer.sdk.lsdka.a.J(LayerClientImpl.java:1224)
     at com.layer.sdk.lsdka.a.f(LayerClientImpl.java:160)
     at com.layer.sdk.lsdka.a$12.a(LayerClientImpl.java:681)
     at com.layer.sdk.lsdka.lsdkk.d.b(ConnectionManager.java:193)
     at com.layer.sdk.lsdka.lsdkk.lsdka.b.c(ConnectionStateMachine.java:106)
     at com.layer.sdk.lsdka.lsdkk.d$1.b(ConnectionManager.java:338)
     at com.layer.lsdka.lsdkc.c.run(RetryableTask.java:193)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)
```

**Comment by andela-wakinsanmi** [comment]
Hello @nicholas-jomo 

You may want to try that in the providerrails flavor.

**Comment by nicholas-jomo** [comment]
@andela-wakinsanmi thanks for quick reply, as in the Messenger [docs](https://github.com/layerhq/Atlas-Android-Messenger). I can simply use atlasProvider to try the demo app. I don't currently have a Heroku setup.

**Comment by andela-wakinsanmi** [comment]
I believe you will need to set up few things before you start. Read https://docs.layer.com/sdk/android/authentication . We are getting rid of providerDemo Flavor in our next release, I will suggest you use the providerrails flavor

**Comment by nicholas-jomo** [comment]
I really appreciate your suggestion. I'm just following your github steps to try the app.

However If the code crashes and not even working, why put it up for us to try? It's a waste of time.

**Comment by andela-wakinsanmi** [comment]
Oops!! sorry about that. I am going to update the read me soon. For the main time, I have pointed you in the right direction. I understand how you feel, please look at the documentation https://docs.layer.com/sdk/android/introduction.

**Comment by nicholas-jomo** [comment]
Thanks again and I appreciate that. Would you be able to tell me how to resolve the crash instead of pointing me to setup the real authentication flow? Your sample app clearly has done all the real setup. All it needs is the FirebaseApp initialization.

Or would you be able to send this issue to a developer who can quickly point out the proper solution? 

Thank you.

**Comment by nicholas-jomo** [comment]
specifically, I added the `FirebaseApp.initializeApp(this);`, the crash still happen

The new code in `App.java`'s `onCreate()`

```
@Override
    public void onCreate() {
        super.onCreate();
        FirebaseApp.initializeApp(this);

        // Enable verbose logging in debug builds
        if (BuildConfig.DEBUG) {
            com.layer.atlas.util.Log.setLoggingEnabled(true);
            com.layer.messenger.util.Log.setAlwaysLoggable(true);
            LayerClient.setLoggingEnabled(this, true);
            LayerClient.setPrivateLoggingEnabled(true);

            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .build());
        }

        if (Log.isPerfLoggable()) {
            Log.perf("Application onCreate()");
        }

        // Allow the LayerClient to track app state
        LayerClient.applicationCreated(this);

        sInstance = this;
    }
```

**Comment by andela-wakinsanmi** [comment]
Can you confirm the package_name in google-services.json

**Comment by nicholas-jomo** [comment]
As in the [docs](https://github.com/layerhq/Atlas-Android-Messenger). I don't need to test the Push Notifications, so I disabled the Google Service plugin. It builds correctly. It just crashes right after I entered my name.

For `providerdemo`, it asks for Name <--- i'm using this
For `providerrail`, it asks for email and password  <-- not this

**Comment by andela-wakinsanmi** [comment]
If you don't need push notifications make sure you set the `useFcm` option to false in `LayerClient.Options`.  Firebase never states that `FirebaseApp.initializeApp` is a required call. I believe the only time you'd need to make that call is if you have a multi-process app.

**Comment by nicholas-jomo** [comment]
Thanks for the suggestion. Didn't really see that in docs.

Now the code block:
```
public static LayerClient getLayerClient() {
        if (sLayerClient == null) {
            // Custom options for constructing a LayerClient
            LayerClient.Options options = new LayerClient.Options()

                    /* Fetch the minimum amount per conversation when first authenticated */
                    .historicSyncPolicy(LayerClient.Options.HistoricSyncPolicy.FROM_LAST_MESSAGE)
                    .useFirebaseCloudMessaging(false)
                    /* Automatically download text and ThreePartImage info/preview */
                    .autoDownloadMimeTypes(Arrays.asList(
                            TextCellFactory.MIME_TYPE,
                            ThreePartImageUtils.MIME_TYPE_INFO,
                            ThreePartImageUtils.MIME_TYPE_PREVIEW));

            // Allow flavor to specify Layer App ID and customize Options.
            sLayerClient = sFlavor.generateLayerClient(sInstance, options);

            // Flavor was unable to generate Layer Client (no App ID, etc.)
            if (sLayerClient == null) return null;

            /* Register AuthenticationProvider for handling authentication challenges */
            sLayerClient.registerAuthenticationListener(getAuthenticationProvider());
        }
        return sLayerClient;
    }
```

And the original error still shows up.

**Comment by andela-wakinsanmi** [comment]
Ok, you may want to check this https://docs.layer.com/sdk/android/push#troubleshooting-and-integration-checklist

**Comment by andela-wakinsanmi** [comment]
You may also want to check Flavor.java in providerdemo, In the method generateLayerClient(), set the option to use firecloud messaging to false.         

options.useFirebaseCloudMessaging(false);

**Comment by nicholas-jomo** [comment]
nice! that's it. it doesn't crash now. Please add this to the ReadMe file if you can, this is gonna save a lot of time for other clients.

Thank you very much 💯
