### ISSUE TITLE
Can not buils

### ISSUE THREAD

**Issue by miroslavign** [layerhq/Atlas-Android-Messenger#6]
Am I missing something here, the project can not even build ?

I followed your info, and after a lot of issues, managed to load it as a module, now I have :

H:\work\android\HEY\Atlas-Android-Messenger\app\src\main\res\values\styles.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'Theme.Atlas.Light'.
Error:(8, 21) No resource found that matches the given name: attr 'AtlasConversationList'.
Error:(9, 21) No resource found that matches the given name: attr 'AtlasMessageComposer'.
Error:(10, 21) No resource found that matches the given name: attr 'AtlasMessageList'.
Error:(11, 21) No resource found that matches the given name: attr 'AtlasParticipantPicker'.
Error:(12, 21) No resource found that matches the given name: attr 'AtlasTypingIndicator'.
H:\work\android\HEY\Atlas-Android-Messenger\app\src\main\res\values-v21\styles.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'Theme.Atlas.Light'.
Error:Execution failed for task ':app:processProviderdemoDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\android-sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

Maybe the source of these errors is in styles file where :
<style name="Theme.Atlas.Base.Light" parent="Theme.AppCompat.Light.DarkActionBar">

an error :
Cannot resolve symbol :    Theme.AppCompat.Light.DarkActionBar

Also, the main issue was importing it as a library:
Gradle 'Atlas-Android-Messenger' project refresh failed
Error:Configuration with name 'default' not found.

**Comment by peter1408** [comment]
exactly!!! after a head aching fight with this module import i am stuck with this same issue!! did any one got the solution would be a great help
