### ISSUE TITLE
connect() first or authenticate() first?

### ISSUE THREAD

**Issue by xiaoleichen** [layerhq/Atlas-Android-Messenger#61]
Your documentation says connect() first, and call authenticate() in onConnectionConnected(). 
Yet in this demo app, it seems authenticate() is called first. 
For example, in the BaseActivity():

@Override

    protected void onResume() {
        super.onResume();
        LayerClient client = App.getLayerClient();
        if (client == null) return;
        if (client.isAuthenticated()) {
            client.connect();
        } else {
            client.authenticate();
        }
    }

So which is it? Or it doesn't matter which one is called first?

**Comment by sriamar** [comment]
@xiaoleichen ,

SDK automatically connects. So, you don't have to call it explicitly anymore. We will get the documents updated. 

Do check your implementation against this checklist. Doing all that will ensure things work fine. https://docs.layer.com/sdk/android/checklist

Thanks,
Amar

**Comment by rajohns08** [comment]
If the SDK automatically connects, why do you still call `.connect()` in this sample app?

**Comment by rajohns08** [comment]
Also, that checklist says 

> Call LayerClient.newInstance asynchronously in Application.onCreate()

But it doesn't appear to be asynchronous in this messenger app.

**Comment by rajohns08** [comment]
@sriamar if I don't explicitly call connect, then my onConnectionConnected callback never hits, and my layerClient always returns isConnected=false
