### ISSUE TITLE
Layer doesn't cache messages

### ISSUE THREAD

**Issue by xiaoleichen** [layerhq/Atlas-Android-Messenger#62]
I integrated this messenger into my app and add a new CellFactory that extends AtlasCellFactory.

The factory needs to fetch information (including pictures) from server and display in a customized layout.

I noticed every time this kind of message scrolls in view, the factory asks for information from server, and renders in the layout. This makes scrolling really slow.

I already use `super(CACHE_SIZE_BYTES); ` in the constructor. CACHES_SIZE_BYTES is set to 256 * 1024 just like in the ThreePartImageFactory.

**Comment by sriamar** [comment]
Hi @xiaoleichen 

> The factory needs to fetch information (including pictures) from server and display in a customized layout.

Is this from Layer server OR your own backend? If it is your own backend, you should do the work to fetch and cache the message. The `ThreePartImageHandler` uses images from Layer SDK, that were fetched and locally cached by Layer SDK.

You can look at what Atlas is doing here by going to https://github.com/layerhq/Atlas-Android/blob/master/layer-atlas/src/main/java/com/layer/atlas/messagetypes/AtlasCellFactory.java

You are welcome to send us PR's with updates, and we are happy to check and merge.

Thanks,
Amar

**Comment by xiaoleichen** [comment]
The image is from my own backend.
I have implemented my own caching mechanism (using LinkedHashMap). It is working really well so far.

Thank you
