### ISSUE TITLE
atlasprovider flavor?

### ISSUE THREAD

**Issue by brianchu** [layerhq/Atlas-Android-Messenger#65]
The flavors:

First of all, I don't see any flavor in IDE, isn't that long time ago they change to Build variants?
 
Also ... atlasprovider: For use in the Layer Atlas demo.  <-- I don't think this atlas provider link work any more.

**Comment by andela-wakinsanmi** [comment]
Hello @brianchu 

Yes, we have updated the read me but it's not been merged to master yet. Please take a look at the read me on  https://github.com/layerhq/Atlas-Android-Messenger/tree/fix_read_me_link_error .
