### ISSUE TITLE
Error when authenticating with provider

### ISSUE THREAD

**Issue by saurabharora90** [layerhq/Atlas-Android-Messenger#76]
I am using the sample identity provider to get the sample app up and running but it doesn't work. The identity provider returns an `identity_token` but the `LayerAuthenticationProvider` module in the sample app seems to be expecting an `authentication_token` along with a `layer_identity_token`. Why is that so? The iOS sample seems to work out of the box.

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).
